### ISSUE TITLE
python code for connecting temperature sensor to raspberry pi

### ISSUE THREAD

**Issue by dvigneshwer** [Seeed-Studio/Grove-RaspberryPi#3]
What are the instructions to connect temperature sensor to raspberry pi board ?

**Comment by lanselambor** [comment]
In this repository only PIR Sensor work with python, I suggest you to look at [GrovePi](http://wiki.seeedstudio.com/wiki/GrovePi+) if you want to use DHT with python even other languages.

**Comment by dvigneshwer** [comment]
![image](https://cloud.githubusercontent.com/assets/5075497/17724969/6064419e-6464-11e6-82d3-8f1027fbe3c3.png)

Source : http://bbs.xiaomi.cn/t-7897152

I don't have a GrovePi, tried the above aproach.
